#!/bin/bash

source /opt/ros/diamondback/setup.bash

#ROS_PACKAGE_PATH=~/Work/rtt_ros_integration_example2:$ROS_PACKAGE_PATH
#ROS_PACKAGE_PATH=~/Work/voltageController:$ROS_PACKAGE_PATH
#ROS_PACKAGE_PATH=~/Work/SVN/PLANEPOWER/TRUNK/orocos:$ROS_PACKAGE_PATH
#source /home/planepower/Work/SVN/PLANEPOWER/TRUNK/tools/cameraRights.sh
source /home/planepower/Work/SVN/PLANEPOWER/TRUNK/tools/envsetup_planepc_ssd.sh
#alias commit = 'svn commit /home/planepower/Work/SVN/PLANEPOWER -m "Autocommit"'
. ~/dotfiles/aliases


