#!/bin/bash

export ROSRELEASE=electric
source /opt/ros/$ROSRELEASE/setup.bash
#source /opt/ros/$ROSRELEASE/stacks/orocos_toolchain_ros/env.sh
source /opt/ros/$ROSRELEASE/stacks/orocos_toolchain/env.sh
export ROS_ROOT=/opt/ros/$ROSRELEASE/ros
export PATH=$ROS_ROOT/bin:$PATH
export PYTHONPATH=$ROS_ROOT/core/roslib/src:$PYTHONPATH
export ROS_PACKAGE_PATH=~/PLANEPOWER/TRUNK/orocos:$ROS_PACKAGE_PATH
