#!/bin/bash

# Modifications to the environment that are machine specific (and probably Drew specific as well).
# For use on whatever machine is currently Drew's primary workstation.

PATH=${PATH}:/usr/local/cuda/bin
PATH=${PATH}:/usr/local/bin
PATH=${PATH}:~/cvpr2011/bin
PATH=${PATH}:/usr/local/cuda/computeprof/bin
PATH=${PATH}:~/src/go/bin
PATH=~/bin:${PATH}
PATH=./:${PATH}
export PATH

# Start with a clean slate
LD_LIBRARY_PATH=

export GOROOT=/home/awagner/go
export GOBIN=$GOROOT/bin
export GOOS=linux
export GOARCH=amd64

export SVN_MERGE=meld

#export INTEL_ROOT=/opt/intel/composerxe-2011.3.174
#source $INTEL_ROOT/bin/compilervars.sh intel64
#export MKL_ROOT=$INTEL_ROOT/mkl/
#export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MKL_ROOT}/lib/intel64/
#export IPP_ROOT=$INTEL_ROOT/ipp/
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${IPP_ROOT}/lib/intel64/
#export ICC_ROOT=$INTEL_ROOT/compiler/
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${ICC_ROOT}/lib/intel64/

export COMPILER=icc
#export COMPILER=g++

export CSCOPE_DB="~/src/cscope.out"

#export MATLAB=/usr/local/bin/MATLAB_R2009a/
#export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MATLAB}/bin/glnxa64
#export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MATLAB}/sys/os/glnxa64
#export AWT_TOOLKIT=MToolkit
#export MATLAB_JAVA=/usr/bin/java

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/computeprof/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
export CUDA_ROOT=/usr/local/cuda
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
export CUDA_ROOT=/usr/local/cuda

export BIT_MODE=64
#export KMP_AFFINITY=granularity=fine,compact,1,0
export OMP_NUM_THREADS=8;

export ACML_BLAS_INCLUDE_DIR=/usr/local/amd/acml4.4.0/ifort64_mp/include/ 
export MATLAB_BLAS_INCLUDE_DIR=${MATLAB}/extern/include
export MKL_BLAS_INCLUDE_DIR=${MKL_ROOT}/include

#export BLAS_IMPLEMENTATION=ACML
#export BLAS_IMPLEMENTATION=MATLAB
export BLAS_IMPLEMENTATION=MKL


