#!/bin/bash
echo ". dotfiles/aliases" >> ~/.bashrc
ln -sf ~/dotfiles/gitconfig			~/.gitconfig
ln -sf ~/dotfiles/vim/vimrc			~/.vimrc
ln -sf ~/dotfiles/vim				~/.vim
ln -sf ~/dotfiles/awesome			~/.config/awesome
ln -sf ~/dotfiles/Xresources		~/.Xresources
ln -sf ~/dotfiles/octave/octaverc	~/.octaverc
